INSERT INTO category (description) VALUES ('Amerykańskie');
INSERT INTO category (description) VALUES ('Włoskie');
INSERT INTO category (description) VALUES ('Meksykańskie');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('łyżeczka');
INSERT INTO unit_of_measure (description) VALUES ('łyżeczka stołowa');
INSERT INTO unit_of_measure (description) VALUES ('kubek');
INSERT INTO unit_of_measure (description) VALUES ('odrobine');
INSERT INTO unit_of_measure (description) VALUES ('szczypta');
INSERT INTO unit_of_measure (description) VALUES ('sztuka');
INSERT INTO unit_of_measure (description) VALUES ('kropla');
INSERT INTO unit_of_measure (description) VALUES ('pół litraS');
